name: Android CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Create local.properties with secret
        run: |
          echo "sdk.dir=" > local.properties
          echo "GEMINIAPIKEY=${{ secrets.GEMINIAPIKEY }}" >> local.properties

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew assembleDebug
