name: Android AI CI



on:
  workflow_dispatch:
    inputs:
      prompt:
        description: "Prompt from Android"
        required: true
        type: string

jobs:
  ai-job:
    runs-on: ubuntu-latest

    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Call Gemini API
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINIAPIKEY }}
        run: |
         for i in {1..5}; do
         echo "Attempt $i"
        
          RESPONSE=$(curl -s -X POST \
            "https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent?key=${GEMINI_API_KEY}" \
            -H "Content-Type: application/json" \
            -d "$(jq -n --arg text "${{ inputs.prompt }}" '{
              contents: [{
                role: "user",
                parts: [{text: $text}]
              }]
            }')")

          echo "$RESPONSE" > response.json

          if jq -e '.candidates[0].content.parts[0].text' response.json > /dev/null; then
             echo "Success"
             break
          fi

          echo "Retrying in 5 seconds..."
          sleep 5
          
          done

      - name: Extract clean text
        run: |
          TEXT=$(cat response.json | jq -r '.candidates[0].content.parts[0].text')

          echo \"$TEXT\" > result.json

      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: ai-result
          path: result.json
